Repository logto-io/swift, pull requests merged in 2022-04, with the labels that each got.

#65 refactor(client): social plugin
  .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
  Package.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
  Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
Labels: enhancement

#66 feat(client): Alipay social plugin
  .github/workflows/main.yml
  .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI_DemoApp.swift
  Demos/SwiftUI Demo/SwiftUI-Demo-Info.plist
  Package.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
  Sources/LogtoSocialPlugin/LogtoSocialPluginError.swift
  Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
  Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
Labels: feature

#68 feat(client): Wechat social plugin
  .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI Demo.entitlements
  Demos/SwiftUI Demo/SwiftUI-Demo-Info.plist
  Package.swift
  Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
  Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
Labels: feature

#71 refactor: validate ID Token after signed in
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
Labels: enhancement

#74 refactor(client): assert constant instead of magic string
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
Labels: enhancement

#76 test(core): add `URLSession` test cases
  Sources/Logto/Extensions/URLSession.swift
  Tests/LogtoTests/URLSessionTests.swift
Labels: testing

#75 refactor(plugin): add `isAvailable`
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
  Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
Labels: enhancement

#73 chore: init readme
  README.md
  logo.png
Labels: chore

#78 fix(client): update `getPostMessage()`
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
Labels: bugfix

#79 refactor(client): support arm64 simulator
  Package.swift
Labels: enhancement

#77 test(client): add LogtoWebViewAuthSession tests
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthSessionTests.swift
Labels: testing

#80 refactor(core): login -> consent
  Sources/Logto/Core/LogtoCore+Generate.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
Labels: enhancement

#84 chore: add LICENSE
  LICENSE.md
Labels: chore

#85 chore: update README
  README.md
Labels: chore

#82 test(client): add tests for `LogtoAuthSession`
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
Labels: testing

#83 test(client): add tests for `LogtoClient`
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
Labels: testing

#81 test(client): add tests for `LogtoWebViewAuthViewController`
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
Labels: testing

#86 fix: SwiftPM build
  .github/workflows/main.yml
  .swiftpm/xcode/xcshareddata/xcschemes/LogtoSDK-Package.xcscheme
  Package.swift
  Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
  Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
Labels: bugfix

#87 feat(ios-sdk): bind wkwebview postMessage method this
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
Labels: feature

#89 refactor(social): align social errors
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Sources/LogtoSocialPlugin/LogtoSocialPlugin.swift
  Sources/LogtoSocialPlugin/LogtoSocialPluginError.swift
  Sources/LogtoSocialPluginAlipay/LogtoSocialPluginAlipay.swift
  Sources/LogtoSocialPluginWeb/LogtoSocialPluginWeb.swift
  Sources/LogtoSocialPluginWechat/LogtoSocialPluginWechat.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
Labels: enhancement

#90 refactor(client): errors
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/LogtoClientErrorTypes.swift
  Sources/LogtoClient/Types/LogtoClientErrors.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
  Sources/LogtoClient/Types/LogtoError.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+Fetch.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
Labels: enhancement

#91 refactor(demo): clean up SwiftUI demo
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI Demo.entitlements
  Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI_DemoApp.swift
  Demos/SwiftUI Demo/SwiftUI-Demo-Info.plist
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
Labels: enhancement

#93 chore: update README
  README.md
Labels: chore

#92 refactor(client): complete with error when manually dismissal
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController+WKNavigationDelegate.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController+WKScriptMessageHandler.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthSessionTests.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
Labels: enhancement

#96 refactor(test): increase post message timeout
  Tests/LogtoClientTests/LogtoAuthSession/LogtoWebViewAuthViewControllerTest.swift
Labels: enhancement

#95 refactor(client): align WebView variable
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
Labels: enhancement

#97 refactor(client): `clientId` -> `appId`
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
  Tests/LogtoClientTests/Types/LogtoConfigTests.swift
Labels: enhancement
