Repository logto-io/swift, pull requests merged in 2022-02, with the labels that each got.

#39 feat: full funcitonal sign in
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Core/LogtoCore+Verify.swift
  Sources/Logto/Extensions/Dictionary.swift
  Sources/Logto/Extensions/URLSession.swift
  Sources/Logto/Types/LogtoErrors.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
  Tests/LogtoTests/LogtoCoreTests+Verify.swift
Labels: feature

#40 feat: use keychain as persist storage
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Package.resolved
  Package.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+PersistStorage.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/AccessToken.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
Labels: feature

#46 chore: fix typo in the GitHub PR template
  .github/pull_request_template.md
Labels: chore

#42 feat: `getIdTokenClaims()`
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Utilities/LogtoUtilities+IdToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
Labels: feature

#41 feat: `signOut()`
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Core/LogtoCore+Revoke.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Sources/LogtoClient/Types/File.swift
  Sources/LogtoClient/Types/LogtoError.swift
Labels: feature

#43 feat: `fetchUserInfo()`
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Types/HttpCompletion.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Tests/LogtoMock/URLSessionMock.swift
Labels: feature

#44 feat: `getAccessToken()`
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Extensions/Dictionary.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+PersistStorage.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/AccessToken.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
Labels: feature

#45 refactor: remove `LogtoCompletion`
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Sources/LogtoClient/Types/File.swift
Labels: enhancement

#47 refactor: add comment for `userinfoEndpoint`
  Sources/Logto/Core/LogtoCore+Fetch.swift
Labels: enhancement

#48 refactor: remove access token persist storage
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+PersistStorage.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
Labels: enhancement

#49 test(client): auth session tests
  .swiftpm/xcode/xcshareddata/xcschemes/Logto SDK-Package.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/LogtoClient.xcscheme
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
  Tests/LogtoMock/NetworkSessionMock.swift
Labels: testing

#51 test(client): add test cases for `.signIn()`
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+Fetch.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
Labels: testing

#52 test(client): add test cases for `.fetchUserInfo()`
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+Fetch.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
  Tests/LogtoMock/NetworkSessionMock.swift
Labels: testing

#53 test(client): add test cases for `.getAccessToken()`
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
Labels: testing

#54 test(client): add test cases
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests.swift
Labels: testing

#55 refactor(core): remove `.sort()` in `.withReservedScopes()`
  Sources/Logto/Utilities/LogtoUtilities.swift
  Tests/LogtoClientTests/Types/LogtoConfigTests.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: enhancement
