Repository logto-io/swift, pull requests merged in 2022-01, with the labels that each got.

#7 feat: `generateState()` and `generateChallenge()`
  .github/pull_request_template.md
  Sources/Logto/Extensions/Data.swift
  Sources/Logto/Extensions/String.swift
  Sources/Logto/LogtoUtilities.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: feature

#8 feat: `decodeIdToken()`
  Sources/Logto/Extensions/Collection.swift
  Sources/Logto/Extensions/String.swift
  Sources/Logto/LogtoUtilities.swift
  Sources/Logto/Types/IdTokenClaims.swift
  Sources/Logto/Types/LogtoErrors.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: feature

#9 feat: `verifyIdToken()`
  Package.resolved
  Package.swift
  Sources/Logto/Extensions/SignatureAlgorithm.swift
  Sources/Logto/LogtoUtilities.swift
  Sources/Logto/Types/JWT.swift
  Sources/Logto/Types/LogtoErrors.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: feature

#11 refactor: support all JWK types
  Sources/Logto/Extensions/Data.swift
  Sources/Logto/LogtoUtilities+IdToken.swift
  Sources/Logto/LogtoUtilities+VerifyJws.swift
  Sources/Logto/LogtoUtilities.swift
  Sources/Logto/Types/IdTokenClaims.swift
  Sources/Logto/Types/LogtoErrors.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: enhancement

#12 refactor: reorg utilities
  Sources/Logto/Utilities/LogtoUtilities+IdToken.swift
  Sources/Logto/Utilities/LogtoUtilities+VerifyJws.swift
  Sources/Logto/Utilities/LogtoUtilities.swift
Labels: enhancement

#13 feat: `generateSignInUrl()`
  Sources/Logto/Core/LogtoCore.swift
  Sources/Logto/Types/LogtoErrors.swift
  Sources/Logto/Types/ValueOrArray.swift
  Tests/LogtoTests/LogtoCoreTests.swift
Labels: feature

#14 chore: add SwiftFormat config
  .swiftformat
  Sources/Logto/Core/LogtoCore.swift
  Sources/Logto/Extensions/Data.swift
  Tests/LogtoTests/LogtoCoreTests.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: chore

#17 feat: `fetchOidcConfig()`
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Types/LogtoErrors.swift
  Sources/Logto/Utilities/LogtoUtilities+IdToken.swift
  Sources/Logto/Utilities/Utilities.swift
  Tests/LogtoTests/LogtoCore+FetchTests.swift
Labels: feature

#18 feat: `generateSignOutUri()`
  Sources/Logto/Core/LogtoCore.swift
  Tests/LogtoTests/LogtoCoreTests+GenerateSignOutUri.swift
Labels: feature

#15 feat: `verifyAndParseSignInCallbackUri()`
  Sources/Logto/Core/LogtoCore.swift
  Sources/Logto/Types/LogtoErrors.swift
  Tests/LogtoTests/LogtoCoreTests.swift
Labels: feature

#20 refactor: reorg structure
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Core/LogtoCore+Verify.swift
  Sources/Logto/Core/LogtoCore.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
  Tests/LogtoTests/LogtoCoreTests+GenerateSignOutUri.swift
  Tests/LogtoTests/LogtoCoreTests+Verify.swift
  Tests/LogtoTests/LogtoCoreTests.swift
Labels: enhancement

#19 feat: `fetchToken()`
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Extensions/URLSession.swift
  Sources/Logto/Protocols/NetworkSession.swift
  Sources/Logto/Types/HttpCompletion.swift
  Sources/Logto/Types/LogtoErrors.swift
  Sources/Logto/Utilities/Utilities.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
  Tests/LogtoTests/URLSessionMock.swift
Labels: feature

#24 chore: fix typo
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
Labels: chore

#21 feat: `fetchUserInfo()`
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Utilities/Utilities.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/URLSessionMock.swift
Labels: feature

#22 feat: `fetchTokenByRefreshToken()`
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
Labels: feature

#23 feat: `revoke()`
  Sources/Logto/Core/LogtoCore+Revoke.swift
  Sources/Logto/Types/HttpCompletion.swift
  Sources/Logto/Utilities/Utilities.swift
  Tests/LogtoTests/LogtoCoreTests+Revoke.swift
  Tests/LogtoTests/URLSessionMock.swift
Labels: feature

#25 feat: init `LogtoClient`
  Package.swift
  Sources/Logto/Logto.swift
  Sources/Logto/Types/ValueOrArray.swift
  Sources/LogtoClient/Types/AccessToken.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
  Tests/LogtoTests/LogtoCoreTests+Verify.swift
  Tests/LogtoTests/LogtoTests.swift
Labels: feature

#26 refactor: use `Int64` over the repo
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Utilities/LogtoUtilities+IdToken.swift
Labels: enhancement

#27 feat: init `LogtoClient`
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/AccessToken.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
Labels: feature

#28 feat: `withReservedScopes()`
  Package.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Utilities/LogtoUtilities.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
  Tests/LogtoClientTests/Types/LogtoConfigTests.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: feature

#31 chore: fix typos in pull request template
  .github/pull_request_template.md
Labels: chore

#30 refactor: LogtoRequest
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Revoke.swift
  Sources/Logto/Extensions/URLSession.swift
  Sources/Logto/Protocols/NetworkSession.swift
  Sources/Logto/Utilities/LogtoRequest.swift
  Sources/Logto/Utilities/LogtoUtilities+IdToken.swift
  Sources/Logto/Utilities/LogtoUtilities.swift
  Sources/Logto/Utilities/Utilities.swift
  Tests/LogtoTests/URLSessionMock.swift
Labels: enhancement

#32 feat(client): fetch OIDC config
  Package.swift
  Sources/Logto/Extensions/URLSession.swift
  Sources/Logto/Protocols/NetworkSession.swift
  Sources/Logto/Types/HttpCompletion.swift
  Sources/Logto/Types/LogtoErrors.swift
  Sources/Logto/Utilities/LogtoRequest.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/LogtoClientErrors.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClient+SignInTests.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClient.swift
  Tests/LogtoClientTests/Types/LogtoConfigTests.swift
  Tests/LogtoMock/URLSessionMock.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Revoke.swift
Labels: feature

#33 feat: init SwiftUI demo
  .swiftpm/xcode/xcshareddata/xcschemes/Logto.xcscheme
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Demos/SwiftUI Demo/SwiftUI Demo/Assets.xcassets/AccentColor.colorset/Contents.json
  Demos/SwiftUI Demo/SwiftUI Demo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Demos/SwiftUI Demo/SwiftUI Demo/Assets.xcassets/Contents.json
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Demos/SwiftUI Demo/SwiftUI Demo/Preview Content/Preview Assets.xcassets/Contents.json
  Demos/SwiftUI Demo/SwiftUI Demo/SwiftUI_DemoApp.swift
  Demos/SwiftUI Demo/SwiftUI DemoTests/SwiftUI_DemoTests.swift
  Demos/SwiftUI Demo/SwiftUI DemoUITests/SwiftUI_DemoUITests.swift
  Demos/SwiftUI Demo/SwiftUI DemoUITests/SwiftUI_DemoUITestsLaunchTests.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
Labels: feature

#34 feat(iOS): `signInWithBrowser()`
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Package.swift
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Utilities/LogtoUtilities.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Sources/LogtoClient/Types/LogtoAuthContext.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
Labels: feature

#36 refactor: remove demo app tests
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI DemoTests/SwiftUI_DemoTests.swift
  Demos/SwiftUI Demo/SwiftUI DemoUITests/SwiftUI_DemoUITests.swift
  Demos/SwiftUI Demo/SwiftUI DemoUITests/SwiftUI_DemoUITestsLaunchTests.swift
Labels: enhancement

#35 refactor: update naming to `resources` and `scopes`
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/Logto/Types/ValueOrArray.swift
  Sources/Logto/Utilities/LogtoUtilities.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/Types/LogtoConfig.swift
  Tests/LogtoClientTests/Types/LogtoConfigTests.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
  Tests/LogtoTests/LogtoUtilitiesTests.swift
Labels: enhancement

#37 feat: sign in error handling
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Core/LogtoCore+Generate.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/Types/LogtoClientErrors.swift
  Tests/LogtoTests/LogtoCoreTests+Generate.swift
Labels: feature
