Repository logto-io/swift, pull requests merged in 2022-03, with the labels that each got.

#56 test(coverage): enable codecov report
  .github/workflows/main.yml
Labels: testing

#57 refactor(client): use webview for auth
  .swiftformat
  BuildTools/Package.swift
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Sources/LogtoClient/Types/TypeAlias.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
Labels: enhancement

#58 refactor: update `self` usage
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
Labels: enhancement

#59 refactor(client): use async
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+Fetch.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
Labels: enhancement

#60 refactor(client): cache get token task
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+AccessToken.swift
  Tests/LogtoMock/NetworkSessionMock.swift
Labels: enhancement

#61 refactor: use async in core
  Demos/SwiftUI Demo/SwiftUI Demo.xcodeproj/project.pbxproj
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Package.swift
  Sources/Logto/Core/LogtoCore+Fetch.swift
  Sources/Logto/Core/LogtoCore+Revoke.swift
  Sources/Logto/Types/LogtoErrors.swift
  Sources/Logto/Utilities/LogtoRequest.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoAuthSession.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthSession.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+AccessToken.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+Fetch.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Tests/LogtoClientTests/LogtoAuthSession/LogtoAuthSessionTests.swift
  Tests/LogtoTests/LogtoCoreTests+Fetch.swift
  Tests/LogtoTests/LogtoCoreTests+Revoke.swift
  Tests/LogtoTests/LogtoCoreTests.swift
Labels: enhancement

#62 refactor: use async for network session and sign in/out
  Demos/SwiftUI Demo/SwiftUI Demo/ContentView.swift
  Sources/Logto/Extensions/URLSession.swift
  Sources/Logto/Protocols/NetworkSession.swift
  Sources/Logto/Types/HttpCompletion.swift
  Sources/Logto/Utilities/LogtoRequest.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignIn.swift
  Sources/LogtoClient/LogtoClient/LogtoClient+SignOut.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignIn.swift
  Tests/LogtoClientTests/LogtoClient/LogtoClientTests+SignOut.swift
  Tests/LogtoMock/NetworkSessionMock.swift
Labels: enhancement

#63 refactor(client): remove unnecessary error enums
  Sources/LogtoClient/LogtoClient/LogtoClient+Errors.swift
Labels: enhancement

#64 feat(client): web social sign in
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewController.swift
  Sources/LogtoClient/LogtoAuthSession/LogtoWebViewAuthViewError.swift
Labels: feature
